preserve_hierarchy: true # to maintain the project structure
pull_request_title: "chore: update translations"
pull_request_labels:
  - translations # pull request label title

files:
  - source: /lib/l10n/app_en.arb # this is needed to the Flutter project
    dest: app.arb # name of the file that Crowdin will create
    translation: /lib/l10n/app_%two_letters_code%.arb # where translations are copied
    update_option: update_as_unapproved # to upload the translations as unapproved